name: mobile_tcc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_analytics: ^12.0.4
  firebase_functions: 0.0.1-dev  
  firebase_database: ^12.1.0
    
  provider: ^6.1.1
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  image_picker: ^1.0.6
  fl_chart: ^1.1.1
  intl: ^0.20.0

  table_calendar: ^3.0.9

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  mocktail: ^1.0.3
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  build_runner: ^2.4.0
  font_awesome_flutter: ^10.7.0
  universal_io: ^2.2.2

  
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/fundo-tcc-mobile.png